[project]
name = "conf-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "openai>=1.54.3",
    "requests>=2.32.3",
    "ruff>=0.7.3",
]
